modmap:
  - name: Laptop keyboard remapping
    device:
      only: "AT Translated Set 2 keyboard"
    remap:
      RIGHTALT: RIGHTCTRL

keymap:
  - name: Open context menu
    remap:
      RIGHTSHIFT-CAPSLOCK: COMPOSE
